### ISSUE TITLE
Maybe sync the same color scheme on Simulator.app? 

### ISSUE THREAD

**Issue by zhangqifan** [DerLobi/XcoatOfPaint#4]

**Comment by DerLobi** [comment]
@zhangqifan Thanks for the suggestion!
I added support for changing the Simulator.app icon in [version 1.2](https://github.com/DerLobi/XcoatOfPaint/releases/tag/1.2).

It doesn't sync to Simulator automatically, because the flow would be annoying to implement for AppStore versions of Xcode.
I opted to implement it so you have to explicitly drag Simulator.app into the XcoatOfPaint app to change it.
You can drag it from the Dock while holding cmd, so you don't have to dive into the contents of Xcode.app to find Simulator.app

<img width="361" alt="dock" src="https://user-images.githubusercontent.com/1935447/118407199-df656c80-b67f-11eb-877e-f418952ed3ba.png">
